- name: "Execute a script on all web server nodes"
  hosts: web_nodes
  tasks:
      - name: add an entry
        lineinfile:
            path: /etc/resolv.conf
            line: "nameserver 10.1.250.10"
      - name: add user
        user:
            name: web_user
            uid: 1040
            group: developers
      - name: "Execute a script on all web server nodes"
        script: /tmp/install_script.sh
      - name: start httpd services
        service: name=httpd state=started
